repo_id: null
dataset: tv
corpus_file: D:/Desktop/repos/relational_graph_llm/py_files/data/corpus/tv_corpus.json
quest_file:  D:/Desktop/repos/relational_graph_llm/py_files/data/tv_QnA_modified.json
chunking_use: rebel
ini_meta_json:   ./outputs/{dataset}/meta_codebook_{chunking_use}.json
saved_examples_name: ./outputs/{dataset}/reasoning_pref_{dataset}.json
final_json_path: ./outputs/{dataset}/reasoning_{dataset}_results.json
seed_n: 20
test_n: 2024
top_m: 20
top_k: 200
combine_ent_sim: 0.93
q_combine_sim: 0.93
aft_combine_sim: 0.93
semantic_overlap_sim: 0.93
reward_func: reward_sbert_inclusive
reward_func_mode: non_llm
